# Generated by Django 2.2 on 2022-09-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('Author', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('Ebookimage', models.ImageField(blank=True, upload_to='assets/images')),
                ('Ebook', models.FileField(blank=True, upload_to='assets/documents')),
            ],
        ),
        migrations.CreateModel(
            name='Bookfeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=300)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
