# Generated by Django 2.2 on 2022-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Ebook',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Ebookimage',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
