# Generated by Django 2.2 on 2022-09-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220907_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookchapters',
            old_name='title',
            new_name='Chapter_title',
        ),
    ]
