# Generated by Django 2.2 on 2022-10-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20221027_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Hardcopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='books.BookCategory'),
        ),
    ]
