# Generated by Django 2.2 on 2022-10-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='books.BookCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
