# Generated by Django 2.2 on 2022-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20221030_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
