# Generated by Django 2.2 on 2022-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20221101_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Digital',
            field=models.BooleanField(default=True),
        ),
    ]
