# Generated by Django 2.2 on 2022-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20221104_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfeatures',
            name='book',
        ),
        migrations.AddField(
            model_name='bookfeatures',
            name='book',
            field=models.ManyToManyField(null=True, to='books.Book'),
        ),
    ]
