# Generated by Django 2.2 on 2022-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sideline',
            field=models.CharField(blank=True, help_text='add a captivating highlight about your Book', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, help_text='not exceeding 400 Words', max_length=300),
        ),
    ]
