# Generated by Django 2.2 on 2022-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
