# Generated by Django 2.2 on 2022-10-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221030_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='customer_that_ordered',
        ),
    ]
