# Generated by Django 2.2 on 2022-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221031_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_review',
            name='customer',
        ),
        migrations.AddField(
            model_name='product_review',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
