# Generated by Django 2.2 on 2022-11-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20221104_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
            preserve_default=False,
        ),
    ]
