# Generated by Django 2.2 on 2022-11-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221104_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_customer_review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
    ]
