# Generated by Django 2.2 on 2022-11-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_rating'),
        ('main', '0021_auto_20221105_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_review',
            name='like',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='love',
        ),
        migrations.CreateModel(
            name='Product_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_liked', models.DateTimeField(auto_now_add=True, null=True)),
                ('like', models.ManyToManyField(related_name='like', to='books.Book')),
                ('love', models.ManyToManyField(related_name='love', to='books.Book')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book')),
            ],
        ),
    ]
