# Generated by Django 2.2 on 2022-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_rating'),
        ('main', '0022_auto_20221105_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='like',
            field=models.ManyToManyField(related_name='like', to='books.Book'),
        ),
        migrations.AddField(
            model_name='product_review',
            name='love',
            field=models.ManyToManyField(related_name='love', to='books.Book'),
        ),
        migrations.DeleteModel(
            name='Product_like',
        ),
    ]
