# Generated by Django 2.2 on 2022-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20221105_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
