# Generated by Django 2.2 on 2022-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20221105_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='books.Book'),
        ),
    ]
