# Generated by Django 2.2 on 2022-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_rating'),
        ('main', '0025_auto_20221116_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='like',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='love',
        ),
        migrations.AddField(
            model_name='product_review',
            name='loves',
            field=models.ManyToManyField(related_name='loves', to='books.Book'),
        ),
    ]
