# Generated by Django 2.2 on 2022-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20221116_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_customer_review',
            name='comment',
            field=models.TextField(blank=True, help_text='not exceeding 40 words', max_length=40),
        ),
        migrations.AlterField(
            model_name='general_customer_review',
            name='image',
            field=models.ImageField(help_text='upload your Face shot', upload_to='media'),
        ),
    ]
